# -*- coding: utf-8 -*-
"""example_a0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E6m38bKmdHCZ7SvBouFpMSjfTKG68TCr

# BBM409 Assignment_0

Group Member: Name Surname

Group Member: Name Surname
"""

""" import necessary libraries"""
import numpy as np

""" upload dataset from your PC, you can use different methods"""
from google.colab import files
data = files.upload()

"""## Pre-processing"""



"""Explain why you use those methods, etc.

## Split the dataset

80% training & 20% test  or 5-fold cross validation

## Classification Methods

In this homework, we use kNN, Naive Bayes ...

### kNN
"""

# import KNeighbors Classifier from sklearn
from sklearn.neighbors import KNeighborsClassifier

"""Explain your results, draw plots, tables etc.

### Naive Bayes
"""



"""Explain your results, draw plots, tables etc."""



